=== citbhav/ACIT-4850-Assignment-1/courses.dtd
<!ELEMENT term (set,day,course+)>
<!ELEMENT set (day,course+)>
<!ATTLIST set
	program CDATA #REQUIRED
	set CDATA #REQUIRED
>
<!ELEMENT day (course+)>
<!ATTLIST day
	code CDATA #REQUIRED
	
>
<!ELEMENT course (name,type,times,instructor,dates,max,act,hrs)>
<!ATTLIST course
	crn CDATA #REQUIRED
	
>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT times (start,end)>
<!ATTLIST times 
	start CDATA #REQUIRED
	end CDATA #REQUIRED
>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT dates (start,end)>
<!ATTLIST dates
	start CDATA #REQUIRED
	end CDATA #REQUIRED
>
<!ELEMENT act (#PCDATA)>
<!ELEMENT hrs (#PCDATA)>
<!ELEMENT max (#PCDATA)>

=== citbhav/ACIT-4850-Assignment-1/bcit.xml
<?xml version="1.0"?>
<!DOCTYPE menu SYSTEM "courses.dtd">
<term>
    <set program="ACIT" set="1 A">
        <day code="Fri">
            <course crn="44279">
                <name>ACIT1420</name>
                <type>A</type>
                <times start="830" end="1120"></times>
                <instructor>"Zhang, Lei"</instructor>
                <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                <max>25</max>
                <act>25</act>
                <hrs>2.83</hrs>
            </course>
        </day>
    </set>
</term>
